# Generated by Django 5.1.2 on 2024-10-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mag_x', models.FloatField()),
                ('mag_y', models.FloatField()),
                ('mag_z', models.FloatField()),
                ('barometro', models.FloatField()),
                ('ruido', models.FloatField()),
                ('giro_x', models.FloatField()),
                ('giro_y', models.FloatField()),
                ('giro_z', models.FloatField()),
                ('acel_x', models.FloatField()),
                ('acel_y', models.FloatField()),
                ('acel_z', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
        migrations.CreateModel(
            name='SensorDataCleaned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mag_x', models.FloatField()),
                ('mag_y', models.FloatField()),
                ('mag_z', models.FloatField()),
                ('barometro', models.FloatField()),
                ('ruido', models.FloatField()),
                ('giro_x', models.FloatField()),
                ('giro_y', models.FloatField()),
                ('giro_z', models.FloatField()),
                ('acel_x', models.FloatField()),
                ('acel_y', models.FloatField()),
                ('acel_z', models.FloatField()),
                ('vibracion', models.FloatField()),
                ('gps_lat', models.FloatField()),
                ('gps_lon', models.FloatField()),
            ],
            options={
                'db_table': 'sensor_data_cleaned',
            },
        ),
    ]
